# Generated by Django 4.1.2 on 2022-12-04 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='orientadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('data_inicio', models.DateTimeField(auto_now=True)),
                ('descricao', models.TextField(max_length=500)),
                ('id_aluno', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autentication.alunos')),
                ('id_orientador', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autentication.orientadores')),
            ],
        ),
        migrations.CreateModel(
            name='email_orientadores',
            fields=[
                ('orien_email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('id_orie', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autentication.orientadores')),
            ],
        ),
        migrations.CreateModel(
            name='email_alunos',
            fields=[
                ('alunos_email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('id_alu', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autentication.alunos')),
            ],
        ),
        migrations.CreateModel(
            name='atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=100)),
                ('id_alunos', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autentication.alunos')),
                ('id_orientadores', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autentication.orientadores')),
                ('id_projetos', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autentication.projetos')),
                ('id_status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autentication.status')),
            ],
        ),
    ]
