# Generated by Django 4.1.2 on 2023-01-22 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autentication', '0002_atividades_usuario_projetos_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_alunos',
            name='id_alu',
        ),
        migrations.RemoveField(
            model_name='email_orientadores',
            name='id_orie',
        ),
        migrations.RemoveField(
            model_name='atividades',
            name='id_alunos',
        ),
        migrations.RemoveField(
            model_name='atividades',
            name='id_orientadores',
        ),
        migrations.RemoveField(
            model_name='atividades',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='id_aluno',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='id_orientador',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='usuario',
        ),
        migrations.AddField(
            model_name='atividades',
            name='aluno',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_atividade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atividades',
            name='orientador',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orientador_atividade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projetos',
            name='aluno',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projetos',
            name='orientador',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orientador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='alunos',
        ),
        migrations.DeleteModel(
            name='email_alunos',
        ),
        migrations.DeleteModel(
            name='email_orientadores',
        ),
        migrations.DeleteModel(
            name='orientadores',
        ),
    ]
