# Generated by Django 4.1.2 on 2023-01-22 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autentication', '0003_remove_email_alunos_id_alu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='status',
        ),
    ]
