# Generated by Django 4.1.2 on 2023-01-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentication', '0004_remove_status_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
