# Generated by Django 4.1.2 on 2023-01-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentication', '0005_status_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividades',
            old_name='id_projetos',
            new_name='projetos',
        ),
        migrations.RenameField(
            model_name='atividades',
            old_name='id_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
