# Generated by Django 4.1.2 on 2023-01-22 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autentication', '0006_rename_id_projetos_atividades_projetos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividades',
            old_name='projetos',
            new_name='projeto',
        ),
    ]
